highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: My Bui
name: My Bui
email: my.bui.fi@gmail.com
email_full: mailto:my.bui.fi@gmail.com
website: mybui.github.io
website_full: https://mybui.github.io
github: https://mybui.github.io

# needed for travis-ci build
exclude: [vendor]
